x=input('what is x?')
#print('x is a', type(x))
print('is x a number?', x.isnumeric())
print('is x an alphabetic?', x.isalpha())
print('is x an alphanumeric?', x.isalnum())
print('is x a space?', x.isspace())
print('is x a digit?', x.isdigit())
print('is x an upper?', x.isupper())
print('is x a lower?', x.islower())
print('is x a decimal', x.isdecimal())
