num=int(input('numero: '))
n=str(num)
print('analisando o numero{}'.format(num))
print('unidade é {}'.format(n[3]))
print('dezena é {}'.format(n[2]))
print('centena é {}'.format(n[1]))
print('milhar {}'.format(n[0]))
